### PR TITLE
FEATURE: Support composer 2+

### PR DESCRIPTION
**Pull request by bwaidelich**
Resolves: #13

### CODE REVIEW

**Comment by bwaidelich** [comment]
Tested with composer *1.10.6*  and *2.0-dev+750a92b4b7aecda0e5b2f9b963f1cb1421900675*

**Review by kdambekalns — APPROVED** [review]
Looks good by reading… Thanks!

**Comment by kdambekalns** [comment]
Oh, what the … we have branches here? 1.0, 2.0 and master? 🤔

**Comment by kdambekalns** [comment]
Sorted it out…

**Pull request merged**
